services:
  client_frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: chutneyads_client_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"  # Changed to match your dev server port
    networks:
      - chutneyads_network
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules

networks:
  chutneyads_network:
    external: true